// Generated by gencpp from file my_robot_msgs/ControlLED.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_CONTROLLED_H
#define MY_ROBOT_MSGS_MESSAGE_CONTROLLED_H

#include <ros/service_traits.h>


#include <my_robot_msgs/ControlLEDRequest.h>
#include <my_robot_msgs/ControlLEDResponse.h>


namespace my_robot_msgs
{

struct ControlLED
{

typedef ControlLEDRequest Request;
typedef ControlLEDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlLED
} // namespace my_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_msgs::ControlLED > {
  static const char* value()
  {
    return "fdb5fdfa0a71721bfde7e4967ca7bd27";
  }

  static const char* value(const ::my_robot_msgs::ControlLED&) { return value(); }
};

template<>
struct DataType< ::my_robot_msgs::ControlLED > {
  static const char* value()
  {
    return "my_robot_msgs/ControlLED";
  }

  static const char* value(const ::my_robot_msgs::ControlLED&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_msgs::ControlLEDRequest> should match 
// service_traits::MD5Sum< ::my_robot_msgs::ControlLED > 
template<>
struct MD5Sum< ::my_robot_msgs::ControlLEDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::ControlLED >::value();
  }
  static const char* value(const ::my_robot_msgs::ControlLEDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::ControlLEDRequest> should match 
// service_traits::DataType< ::my_robot_msgs::ControlLED > 
template<>
struct DataType< ::my_robot_msgs::ControlLEDRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::ControlLED >::value();
  }
  static const char* value(const ::my_robot_msgs::ControlLEDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_msgs::ControlLEDResponse> should match 
// service_traits::MD5Sum< ::my_robot_msgs::ControlLED > 
template<>
struct MD5Sum< ::my_robot_msgs::ControlLEDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_msgs::ControlLED >::value();
  }
  static const char* value(const ::my_robot_msgs::ControlLEDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_msgs::ControlLEDResponse> should match 
// service_traits::DataType< ::my_robot_msgs::ControlLED > 
template<>
struct DataType< ::my_robot_msgs::ControlLEDResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_msgs::ControlLED >::value();
  }
  static const char* value(const ::my_robot_msgs::ControlLEDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_CONTROLLED_H
