// Generated by gencpp from file my_robot_msgs/ControlLEDRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_CONTROLLEDREQUEST_H
#define MY_ROBOT_MSGS_MESSAGE_CONTROLLEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct ControlLEDRequest_
{
  typedef ControlLEDRequest_<ContainerAllocator> Type;

  ControlLEDRequest_()
    : LED_num(0)
    , state(0)  {
    }
  ControlLEDRequest_(const ContainerAllocator& _alloc)
    : LED_num(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int64_t _LED_num_type;
  _LED_num_type LED_num;

   typedef int64_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlLEDRequest_

typedef ::my_robot_msgs::ControlLEDRequest_<std::allocator<void> > ControlLEDRequest;

typedef boost::shared_ptr< ::my_robot_msgs::ControlLEDRequest > ControlLEDRequestPtr;
typedef boost::shared_ptr< ::my_robot_msgs::ControlLEDRequest const> ControlLEDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_robot_msgs': ['/home/tg/catkin_ws/src/my_robot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1964d81a9626a0f439e01b0542f62619";
  }

  static const char* value(const ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1964d81a9626a0f4ULL;
  static const uint64_t static_value2 = 0x39e01b0542f62619ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/ControlLEDRequest";
  }

  static const char* value(const ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 LED_num\n\
int64 state\n\
";
  }

  static const char* value(const ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LED_num);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlLEDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::ControlLEDRequest_<ContainerAllocator>& v)
  {
    s << indent << "LED_num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.LED_num);
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_CONTROLLEDREQUEST_H
